services:

    # Handlers
    symfony_ag_grid_bundle.where_part_handler:
        class: Skrepr\SymfonyAgGridBundle\Handler\WherePartHandler
        arguments:
          ['@symfony_ag_grid_bundle.filter_type_converter_context']

    symfony_ag_grid_bundle.order_by_part_handler:
        class: Skrepr\SymfonyAgGridBundle\Handler\OrderByPartHandler

    symfony_ag_grid_bundle.filter_handler:
        class: Skrepr\SymfonyAgGridBundle\Handler\FilterHandler
        arguments:
          ['@symfony_ag_grid_bundle.where_part_handler', '@symfony_ag_grid_bundle.order_by_part_handler']

    symfony_ag_grid_bundle.grid_handler:
        class: Skrepr\SymfonyAgGridBundle\Handler\GridHandler

    # Grid context
    symfony_ag_grid_bundle.grid_context:
        class: Skrepr\SymfonyAgGridBundle\Context\GridContext

    Skrepr\SymfonyAgGridBundle\Context\GridContext: '@symfony_ag_grid_bundle.grid_context'

    # Converter context
    symfony_ag_grid_bundle.converter_context:
        class: Skrepr\SymfonyAgGridBundle\Context\ConverterContext

    Skrepr\SymfonyAgGridBundle\Context\ConverterContext: '@symfony_ag_grid_bundle.converter_context'

    # Filter type converter context
    symfony_ag_grid_bundle.filter_type_converter_context:
        class: Skrepr\SymfonyAgGridBundle\Context\FilterTypeConverterContext

    Skrepr\SymfonyAgGridBundle\Context\FilterTypeConverterContext: '@symfony_ag_grid_bundle.filter_type_converter_context'

    # Grid builder
    symfony_ag_grid_bundle.grid_builder:
        class: Skrepr\SymfonyAgGridBundle\Data\Grid\GridBuilder
        arguments:
          ['@symfony_ag_grid_bundle.filter_handler', '@symfony_ag_grid_bundle.grid_handler']

    Skrepr\SymfonyAgGridBundle\Data\Grid\GridBuilder: '@symfony_ag_grid_bundle.grid_builder'

    # Grid manager
    symfony_ag_grid_bundle.grid_manager:
        class: Skrepr\SymfonyAgGridBundle\Data\Grid\GridManager
        arguments:
          ['@symfony_ag_grid_bundle.grid_context', '@symfony_ag_grid_bundle.converter_context', '@symfony_ag_grid_bundle.grid_builder']

    Skrepr\SymfonyAgGridBundle\Data\Grid\GridManager: '@symfony_ag_grid_bundle.grid_manager'

    # Default included bundle converters
    Skrepr\SymfonyAgGridBundle\Converter\:
        resource: '../../Converter/*'
        tags: [ ag_grid_bundle_converter ]

    # Default AgGrid filter converters
    Skrepr\SymfonyAgGridBundle\Data\Filter\Converter\:
        resource: '../../Data/Filter/Converter/*'
        tags: [ ag_grid_bundle_filter_type_converter ]